name: get IP or domain info
on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'IP'
        required: false
      domain:
        description: 'Domain'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install mmdbinspect
        run: |
          downloadUrl=$(curl -sLRJ "https://api.github.com/repos/maxmind/mmdbinspect/releases/latest" | jq -r ".assets[].browser_download_url" | grep "amd64\.deb")
          curl -sLRJO "$downloadUrl"
          sudo dpkg -i mmdbinspect*.deb

      - name: get ips by domain
        if: ${{ github.event.inputs.domain != '' }}
        run: |
          dig "${{ github.event.inputs.domain }}" +short -4 | grep -v '\.$' >> ip.txt

      - name: save request ip into temp file
        if: ${{ github.event.inputs.ip != '' }}
        run: |
          echo ${{ github.event.inputs.ip }} >> ip.txt

      - name: get IP info
        run: |
          cat ip.txt | xargs mmdbinspect -db ./GeoLite2-ASN/GeoLite2-ASN.mmdb -db ./GeoLite2-Country/GeoLite2-Country.mmdb -db ./GeoLite2-City/GeoLite2-City.mmdb
