name: get IP info
on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'IP'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install mmdbinspect
        run: |
          downloadUrl=$(curl -sX GET "https://api.github.com/repos/maxmind/mmdbinspect/releases/latest" | jq -r ".assets[].browser_download_url" | grep "amd64\.deb")
          curl -so "mmdbinspect.deb" "$downloadUrl"
          dpkg -i

      - name: get IP info
        run: |
          mmdbinspect -db ./GeoLite2-ASN/GeoLite2-ASN.mmdb -db ./GeoLite2-Country/GeoLite2-Country.mmdb -db ./GeoLite2-City/GeoLite2-City.mmdb "${{ github.event.inputs.ip }}"
