name: update ipset
on:
  workflow_dispatch:
  schedule:
    - cron: '30 */12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install ipset
        run: |
          sudo apt install ipset

      - name: update ipset of CHINA_IP
        run: |
          curl -o /tmp/ip_cidr.txt https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
          ipsetName=CHINA_IP
          mkdir -p ipset
          echo "create $ipsetName hash:net" >./ipset/ipset-$ipsetName.txt
          while IFS= read -r line; do
            echo "add $ipsetName $line" >>./ipset/ipset-$ipsetName.txt
          done </tmp/ip_cidr.txt
          rm /tmp/ip_cidr.txt

      - name: update ipset of CLOUDFLARENET
        run: |
          csvgrep -c autonomous_system_organization -r "^CLOUDFLARENET$" ./GeoLite2-ASN-CSV/GeoLite2-ASN-Blocks-IPv4.csv | csvcut -c network | sed 1d >/tmp/ip_cidr.txt
          ipsetName=CLOUDFLARENET
          mkdir -p ipset
          echo "create $ipsetName hash:net" >./ipset/ipset-$ipsetName.txt
          while IFS= read -r line; do
            echo "add $ipsetName $line" >>./ipset/ipset-$ipsetName.txt
          done </tmp/ip_cidr.txt
          rm /tmp/ip_cidr.txt

      - name: update ipset of ORACLE-BMC-31898
        run: |
          csvgrep -c autonomous_system_organization -r "^ORACLE-BMC-31898$" ./GeoLite2-ASN-CSV/GeoLite2-ASN-Blocks-IPv4.csv | csvcut -c network | sed 1d >/tmp/ip_cidr.txt
          ipsetName=ORACLE-BMC-31898
          mkdir -p ipset
          echo "create $ipsetName hash:net" >./ipset/ipset-$ipsetName.txt
          while IFS= read -r line; do
            echo "add $ipsetName $line" >>./ipset/ipset-$ipsetName.txt
          done </tmp/ip_cidr.txt
          rm /tmp/ip_cidr.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
